id: P003001
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16556
  title: ཤེལ་དཀར་ཆོས་འབྱུང་།
  author: ''
  volumes:
    c730877b46424552b3136935fd106091:
      image_group_id: I2PD18843
      title: ''
      volume_number: 1
      total_pages: 290
      base_file: v001.txt
