id: I6EC36E34
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T02:08:14+00:00'
last_modified: '2022-06-07T16:54:42.714893+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16556
  title: ཤེལ་དཀར་ཆོས་འབྱུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    CCBC:
      image_group_id: I2PD18843
      title: ''
      total_pages: 290
      order: 1
      base_file: CCBC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
